### ISSUE TITLE
NullpointerException in canPush

### ISSUE THREAD

**Issue by JennStro** [inf112-v20/error_brain_not_found#203]
Fant en bug. :( 

Tror det har noe å gjøre med backup, men skjønte ikke hvor det kom fra. 

**Player 1 played Back up: 840
Player 2 played Back up: 700
Exception in thread "Thread-3" java.lang.NullPointerException
	at inf112.skeleton.app.board.BoardLogic.canPush(BoardLogic.java:232)
	at inf112.skeleton.app.board.Board.movePlayer(Board.java:218)
	at inf112.skeleton.app.RallyGame.playCard(RallyGame.java:476)
	at inf112.skeleton.app.RallyGame.allPlayersPlayCard(RallyGame.java:452)
	at inf112.skeleton.app.RallyGame.doTurn(RallyGame.java:274)
	at java.base/java.lang.Thread.run(Thread.java:834)**

**Comment by JennStro** [comment]
Tror jeg fant ut av det! Måtte endre direction i shouldPush når player går bakover
